// Copyright 2026 Hemi Labs, Inc.
// This file is part of the go-ethereum library.
//
// The go-ethereum library is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// The go-ethereum library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with the go-ethereum library. If not, see <http://www.gnu.org/licenses/>.

package types

import (
	"encoding/hex"
	"encoding/json"
	"math/big"
	"testing"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/rlp"
)

// Test vector produced by upstream go-ethereum v1.17.7 (the client release required for
// the Sepolia Glamsterdam activation) for a post-Amsterdam header carrying both the
// EIP-7928 blockAccessListHash and the EIP-7843 slotNumber fields. The RLP encoding, the
// JSON encoding (as served over eth_getBlockByNumber) and the canonical hash were all
// generated by upstream, so this test pins byte-level compatibility with real L1 headers.
const (
	amsterdamHeaderRLP  = "f90283a00000000000000000000000000000000000000000000000000000000000000001a01dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347940000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000002a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421b90100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008083989680840393870080846ac4fd6080a0000000000000000000000000000000000000000000000000000000000000000088000000000000000007a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b4218080a00000000000000000000000000000000000000000000000000000000000000000a0e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855a0ba0100000000000000000000000000000000000000000000000000000000000083ac6000"
	amsterdamHeaderJSON = `{"parentHash":"0x0000000000000000000000000000000000000000000000000000000000000001","sha3Uncles":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347","miner":"0x0000000000000000000000000000000000000000","stateRoot":"0x0000000000000000000000000000000000000000000000000000000000000002","transactionsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","receiptsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","difficulty":"0x0","number":"0x989680","gasLimit":"0x3938700","gasUsed":"0x0","timestamp":"0x6ac4fd60","extraData":"0x","mixHash":"0x0000000000000000000000000000000000000000000000000000000000000000","nonce":"0x0000000000000000","baseFeePerGas":"0x7","withdrawalsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","blobGasUsed":"0x0","excessBlobGas":"0x0","parentBeaconBlockRoot":"0x0000000000000000000000000000000000000000000000000000000000000000","requestsHash":"0xe3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855","blockAccessListHash":"0xba01000000000000000000000000000000000000000000000000000000000000","slotNumber":"0xac6000","hash":"0x8a5873e9569d658c029c64934fb5136ae61f51824ad0658499010864ae39b9c1"}`
	amsterdamHeaderHash = "0x8a5873e9569d658c029c64934fb5136ae61f51824ad0658499010864ae39b9c1"
	amsterdamSlotNumber = uint64(11296768)
)

func amsterdamHeaderBALHash() common.Hash {
	return common.Hash{0xba, 0x01}
}

// TestAmsterdamHeaderRLPCompatibility checks that an upstream Amsterdam header decodes,
// hashes and re-encodes identically with this fork's Header type.
func TestAmsterdamHeaderRLPCompatibility(t *testing.T) {
	enc, err := hex.DecodeString(amsterdamHeaderRLP)
	if err != nil {
		t.Fatal(err)
	}
	var h Header
	if err := rlp.DecodeBytes(enc, &h); err != nil {
		t.Fatalf("decoding upstream Amsterdam header: %v", err)
	}
	if h.BlockAccessListHash == nil || *h.BlockAccessListHash != amsterdamHeaderBALHash() {
		t.Fatalf("blockAccessListHash: have %v, want %s", h.BlockAccessListHash, amsterdamHeaderBALHash())
	}
	if h.SlotNumber == nil || *h.SlotNumber != amsterdamSlotNumber {
		t.Fatalf("slotNumber: have %v, want %d", h.SlotNumber, amsterdamSlotNumber)
	}
	if have := h.Hash().Hex(); have != amsterdamHeaderHash {
		t.Fatalf("hash: have %s, want %s", have, amsterdamHeaderHash)
	}
	reenc, err := rlp.EncodeToBytes(&h)
	if err != nil {
		t.Fatal(err)
	}
	if hex.EncodeToString(reenc) != amsterdamHeaderRLP {
		t.Fatalf("re-encoded RLP differs from upstream encoding")
	}
	// The Amsterdam header has 23 RLP list elements: the 21 Prague fields plus the two new ones.
	var fields []rlp.RawValue
	if err := rlp.DecodeBytes(enc, &fields); err != nil {
		t.Fatal(err)
	}
	if len(fields) != 23 {
		t.Fatalf("Amsterdam header has %d RLP fields, want 23", len(fields))
	}
}

// TestAmsterdamHeaderJSONCompatibility checks that the JSON form served by an upstream
// node over eth_getBlockByNumber decodes into a Header that hashes to the canonical hash,
// which is what every op-node style hash check relies on.
func TestAmsterdamHeaderJSONCompatibility(t *testing.T) {
	var h Header
	if err := json.Unmarshal([]byte(amsterdamHeaderJSON), &h); err != nil {
		t.Fatalf("decoding upstream Amsterdam header JSON: %v", err)
	}
	if have := h.Hash().Hex(); have != amsterdamHeaderHash {
		t.Fatalf("hash from JSON: have %s, want %s", have, amsterdamHeaderHash)
	}
	// Marshal again and make sure both fields are emitted with upstream's names.
	out, err := json.Marshal(&h)
	if err != nil {
		t.Fatal(err)
	}
	var m map[string]json.RawMessage
	if err := json.Unmarshal(out, &m); err != nil {
		t.Fatal(err)
	}
	if string(m["blockAccessListHash"]) != `"`+amsterdamHeaderBALHash().Hex()+`"` {
		t.Fatalf("blockAccessListHash JSON: have %s", m["blockAccessListHash"])
	}
	if string(m["slotNumber"]) != `"0xac6000"` {
		t.Fatalf("slotNumber JSON: have %s, want \"0xac6000\"", m["slotNumber"])
	}
	// Round-tripping through JSON must preserve the hash.
	var back Header
	if err := json.Unmarshal(out, &back); err != nil {
		t.Fatal(err)
	}
	if back.Hash() != h.Hash() {
		t.Fatalf("JSON round trip changed the hash")
	}
}

// TestAmsterdamHeaderCopy checks that CopyHeader deep-copies the new fields.
func TestAmsterdamHeaderCopy(t *testing.T) {
	var h Header
	if err := json.Unmarshal([]byte(amsterdamHeaderJSON), &h); err != nil {
		t.Fatal(err)
	}
	cpy := CopyHeader(&h)
	if cpy.Hash() != h.Hash() {
		t.Fatalf("copy hashes differently from original")
	}
	if cpy.BlockAccessListHash == nil || *cpy.BlockAccessListHash != *h.BlockAccessListHash || cpy.SlotNumber == nil || *cpy.SlotNumber != *h.SlotNumber {
		t.Fatalf("copy lost the Amsterdam fields")
	}
	if cpy.BlockAccessListHash == h.BlockAccessListHash || cpy.SlotNumber == h.SlotNumber {
		t.Fatalf("copy aliases the original's pointers")
	}
	// Each new field is part of the hash, and mutating the copy must not touch the original.
	*cpy.SlotNumber++
	if *h.SlotNumber != amsterdamSlotNumber {
		t.Fatalf("mutating the copy's slotNumber changed the original")
	}
	if cpy.Hash() == h.Hash() {
		t.Fatalf("slotNumber must be part of the hash")
	}
	*cpy.SlotNumber--
	cpy.BlockAccessListHash[0] ^= 0xff
	if *h.BlockAccessListHash != amsterdamHeaderBALHash() {
		t.Fatalf("mutating the copy's blockAccessListHash changed the original")
	}
	if cpy.Hash() == h.Hash() {
		t.Fatalf("blockAccessListHash must be part of the hash")
	}
	// Block accessors return copies as well.
	b := NewBlockWithHeader(&h)
	if *b.SlotNumber() != amsterdamSlotNumber || *b.BlockAccessListHash() != amsterdamHeaderBALHash() {
		t.Fatalf("block accessors returned wrong values")
	}
	if b.SlotNumber() == h.SlotNumber {
		t.Fatalf("Block.SlotNumber aliases the header")
	}
}

// TestLegacyHeaderEncodingUnchanged checks that headers without the Amsterdam fields keep
// their pre-Amsterdam encoding and hash, so existing L2 blocks are unaffected.
func TestLegacyHeaderEncodingUnchanged(t *testing.T) {
	var h Header
	if err := json.Unmarshal([]byte(amsterdamHeaderJSON), &h); err != nil {
		t.Fatal(err)
	}
	h.BlockAccessListHash, h.SlotNumber = nil, nil
	enc, err := rlp.EncodeToBytes(&h)
	if err != nil {
		t.Fatal(err)
	}
	var fields []rlp.RawValue
	if err := rlp.DecodeBytes(enc, &fields); err != nil {
		t.Fatal(err)
	}
	if len(fields) != 21 {
		t.Fatalf("legacy header has %d RLP fields, want 21 (no Amsterdam placeholders)", len(fields))
	}
	var back Header
	if err := rlp.DecodeBytes(enc, &back); err != nil {
		t.Fatal(err)
	}
	if back.BlockAccessListHash != nil || back.SlotNumber != nil {
		t.Fatalf("legacy decode populated Amsterdam fields")
	}
	if back.Hash() != h.Hash() {
		t.Fatalf("legacy round trip changed the hash")
	}
	// Pre-London / pre-Shanghai headers (no optional fields at all) are untouched too.
	old := &Header{Number: big.NewInt(1), Difficulty: big.NewInt(2), GasLimit: 3, Extra: []byte{}}
	enc, err = rlp.EncodeToBytes(old)
	if err != nil {
		t.Fatal(err)
	}
	if err := rlp.DecodeBytes(enc, &fields); err != nil {
		t.Fatal(err)
	}
	if len(fields) != 15 {
		t.Fatalf("pre-London header has %d RLP fields, want 15", len(fields))
	}
	// A JSON header without the new keys must not get them either.
	var fromJSON Header
	if err := json.Unmarshal([]byte(`{"parentHash":"0x0000000000000000000000000000000000000000000000000000000000000000","sha3Uncles":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347","miner":"0x0000000000000000000000000000000000000000","stateRoot":"0x0000000000000000000000000000000000000000000000000000000000000000","transactionsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","receiptsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","logsBloom":"0x`+hex.EncodeToString(make([]byte, 256))+`","difficulty":"0x0","number":"0x1","gasLimit":"0x1","gasUsed":"0x0","timestamp":"0x1","extraData":"0x","mixHash":"0x0000000000000000000000000000000000000000000000000000000000000000","nonce":"0x0000000000000000","baseFeePerGas":"0x7"}`), &fromJSON); err != nil {
		t.Fatal(err)
	}
	if fromJSON.BlockAccessListHash != nil || fromJSON.SlotNumber != nil {
		t.Fatalf("legacy JSON populated Amsterdam fields")
	}
}

// TestEmptyBlockAccessListHash pins the EIP-7928 empty-list commitment, keccak256(rlp([])).
func TestEmptyBlockAccessListHash(t *testing.T) {
	if have := rlpHash([]interface{}{}); have != EmptyBlockAccessListHash {
		t.Fatalf("EmptyBlockAccessListHash: have %s, want %s", have, EmptyBlockAccessListHash)
	}
}

// TestAmsterdamHeaderPartialFieldEncoding pins the optional-field placeholder behaviour of
// the generated RLP encoder for every combination of the two new fields, including the
// pre-fork form of the upstream vector, with hashes cross-checked against upstream
// go-ethereum v1.17.7 so a future codec regeneration cannot silently change them.
func TestAmsterdamHeaderPartialFieldEncoding(t *testing.T) {
	var base Header
	if err := json.Unmarshal([]byte(amsterdamHeaderJSON), &base); err != nil {
		t.Fatal(err)
	}
	bal, slot := *base.BlockAccessListHash, *base.SlotNumber
	tests := []struct {
		name      string
		bal       *common.Hash
		slot      *uint64
		fields    int
		hash      string
		decodes   bool
		field21Is string // hex of the 22nd element, when present
	}{
		{"pre-fork (neither field)", nil, nil, 21, "0x674ef048b9dc0acfb0837431fddf9bf19b689effe7207df912cbf774899338be", true, ""},
		{"both fields", &bal, &slot, 23, amsterdamHeaderHash, true, "a0" + hex.EncodeToString(bal[:])},
		{"only blockAccessListHash", &bal, nil, 22, "0x8fec385a548ca43ad8b2aaeb30f950b9aedbd97ae7f1dc583e0ec40ab4e8d6c6", true, "a0" + hex.EncodeToString(bal[:])},
		// Only slotNumber: the encoder writes an empty-string placeholder (0x80) for the
		// missing access-list hash, exactly like upstream, and decoding that form fails in
		// upstream too (a 0-byte string is not a valid common.Hash). Consensus requires
		// both-or-neither, so this shape never occurs on chain.
		{"only slotNumber", nil, &slot, 23, "0xc39ed3ec6fdd5576a6e14ae1df6a499d73e3537c69dff5f200e1dcf188402003", false, "80"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			h := CopyHeader(&base)
			h.BlockAccessListHash, h.SlotNumber = tt.bal, tt.slot
			enc, err := rlp.EncodeToBytes(h)
			if err != nil {
				t.Fatal(err)
			}
			var fields []rlp.RawValue
			if err := rlp.DecodeBytes(enc, &fields); err != nil {
				t.Fatal(err)
			}
			if len(fields) != tt.fields {
				t.Fatalf("fields: have %d, want %d", len(fields), tt.fields)
			}
			if have := h.Hash().Hex(); have != tt.hash {
				t.Fatalf("hash: have %s, want %s", have, tt.hash)
			}
			if tt.field21Is != "" && hex.EncodeToString(fields[21]) != tt.field21Is {
				t.Fatalf("field 21: have %x, want %s", fields[21], tt.field21Is)
			}
			var back Header
			err = rlp.DecodeBytes(enc, &back)
			if tt.decodes && err != nil {
				t.Fatalf("decode: %v", err)
			}
			if !tt.decodes && err == nil {
				t.Fatalf("decode succeeded, expected an error for the placeholder form")
			}
			if tt.decodes && back.Hash() != h.Hash() {
				t.Fatalf("round trip changed the hash")
			}
		})
	}
}
