# Copyright (c) 2024 Hemi Labs, Inc.
# Use of this source code is governed by the MIT License,
# which can be found in the LICENSE file.

# GitHub Actions workflow to publish Docker images.
name: "Docker"
on:
  push:
  workflow_dispatch:

concurrency:
  group: "docker-${{ github.workflow }}-${{ github.event.number || github.ref }}"
  cancel-in-progress: true

jobs:
  # Build and publish Docker image
  docker:
    name: "Docker"
    if: ${{ github.repository_owner == 'hemilabs' }}
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
      packages: write
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: "Setup QEMU"
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0

      - name: "Setup Docker Buildx"
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: "Login to DockerHub"
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: "ghcr.io"
          username: "${{ github.repository_owner }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Prepare"
        id: "prepare"
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
          echo "build_date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> "$GITHUB_OUTPUT"

      - name: "Build and push"
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: "${{ github.workspace }}"
          platforms: "amd64"
          file: "${{ github.workspace }}/Dockerfile"
          push: true
          build-args: |
            VERSION=${{ steps.prepare.outputs.sha_short }}
            VCS_REF=${{ github.sha }}
            BUILD_DATE=${{ steps.prepare.outputs.build_date }}
          tags: |
            hemilabs/op-geth:${{ steps.prepare.outputs.sha_short }}
            ghcr.io/hemilabs/op-geth:${{ steps.prepare.outputs.sha_short }}
